services:
  kong-migrations:
    image: kong/kong-gateway:3.7
    command: kong migrations bootstrap
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PASSWORD: kong
    restart: "no"

  kong:
    depends_on:
      kong-migrations:
        condition: service_completed_successfully
